---
name: PR - Commit
on:
  pull_request: {}

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run checks
        run: echo "this should run checks based on the commits in the PR"
